### PR TITLE
Add scattered moonlight to dark sky surface brightness

### PR DESCRIPTION
**Pull request by dkirkby**
For a description of the method and plots see #9.

### CODE REVIEW

**Comment by dkirkby** [comment]
Update docs for this PR are at http://specsim.readthedocs.org/en/ks_moon/

**Comment by dkirkby** [comment]
I just checked that this branch does not break or change the results of `quickbrick` and `quickgen` (using the methodology of desihub/desisim#80).

**Comment by dkirkby** [comment]
I am ready to merge this now but let me know if you would like more time to look it over first.

**Comment by sbailey** [comment]
Thanks for the new features and updated docs.  OK with me for you to merge this.

**Pull request merged**
