### PR TITLE
fiberloss method is updated for dithering simulations

### PR DESCRIPTION
**Pull request by tolgayapici**
the previous branch, dithering, was off sync with master and would be hard to resolve the conflicts. created a new branch out of master and added the features needed for dithering simulations.

### CODE REVIEW

**Comment by sbailey** [comment]
@dkirkby could you take a look at the failing Travis tests?  They appear to be related to matplotlib / astropy / numpy version incompatibilities, and not directly to this code update (and not just Travis hiccups either).

In addition to the Travis tests, could you also review this PR for merging?  Thanks.

**Comment by weaverba137** [comment]
@tolgayapici, @dkirkby, does this PR supersede #73?

**Comment by dkirkby** [comment]
I suspect this PR is no longer relevant but @tolgayapici should confirm.

**Comment by sybenzvi** [comment]
@dkirkby and @weaverba137, Tolga left DESI at the end of November 2019 and is not maintaining the branch. Given the progress Eddie made using actual dither data we don't really need to merge this into the master. You can close the PR but I suggest keeping the branch around just in case.

**Comment by weaverba137** [comment]
Closing PR based on @sybenzvi's advice.

**Pull request closed without merging**
