### PR TITLE
Correct output resolution matrix

### PR DESCRIPTION
**Pull request by p-slash**
This PR redesigns the test for the new resolution matrix output by comparing each row to theoretically expected values.

### CODE REVIEW

**Comment by weaverba137** [comment]
@julienguy, could you please review this? it is possible this fixes #137.

**Comment by weaverba137** [comment]
I have rebased this branch on main so that test will now run automatically.

**Comment by p-slash** [comment]
Thanks @weaverba137 . This fix was needed after PR #128 where I changed how the input resolution matrix was downsampled to DESI resolution. It compares the downsampled resolution matrix to theoretical expectations, though a relative tolerance of 0.1% is needed to pass this test.

As far as I know, these two PRs affect **only** Lya forest P1D, and we have been happy about it.

**Comment by weaverba137** [comment]
@p-slash, OK, if you have no objections, I'll clean up and merge this PR.

**Comment by weaverba137** [comment]
I'm also adding a quick fix for #133.

**Comment by p-slash** [comment]
No objections. Thanks

**Pull request merged**
