### PR TITLE
Fast fiber acceptance

### PR DESCRIPTION
**Pull request by julienguy**
Implementation of a fast fiber acceptance computation trained on galsim.
 - new file fitgalsim.py: script that runs the fiber acceptance estimation with galsim for a large number of fiber locations, seeing values, wavelength, and for various sources: point sources , disk and bulge profiles with a range of half light radii. It compresses all of this info in 2D and 3D fits images which contain the average and rms fiber acceptance, for each source type (POINT,DISK,BULGE), as a function of fiber offset in um, effective sigma in um, and half light radius for the extended sources. The output file is saved in $DESIMODEL/data/throughput/galsim-fiber-acceptance.fits.
 - new file fastfiberacceptance.py: reads galsim-fiber-acceptance.fits , instantiates 2D and 3D interpolations
 - modifications to fiberloss.py instrument.py : add the new "fastsim" method  
 - modifications to data/config/desi.yaml : "fastsim" method is the default

This approach permits to use all of the throughput correlations introduced by plate scale, telescope PSF, seeing , chromatic aberrations, correlated fiber positioning errors developed in specsim while minimizing the computation time and removing the galsim dependency. It is accurate at the percent level which largely sufficient.

As a example, the following image shows the variation of throughput for stars, at 4000A and 9000A, for a seeing of 1.1 arcsec. The patches are due to the correlated fiber offsets, while the radial effect is a combination of plate scale variation and chromatic aberrations. Interestingly, for a seeing of 2 arcsec, all variations due to fiber offsets are washed out and we are left with the plate scale variation.
star_qso_4000a_1 1arcsec
star_qso_9000a_1 1arcsec

### CODE REVIEW

**Comment by julienguy** [comment]
More work needed for the script fitgalsim (I am replacing the Monte Carlo by a fixed grid of sigma offset which requires a bit of reverse engineering). So, please wait before pushing this PR once the installation issues are solved.

**Comment by dkirkby** [comment]
Travis tests are all passing now.

**Comment by dkirkby** [comment]
Some suggestions before we merge this PR:

1. Document the new fitgalsim script and fastfiberacceptance module in `docs/fiberloss.rst`.  You can see the current (automatically built) version [here](http://specsim.readthedocs.io/en/latest/fiberloss.html).

2. Add some unit tests of the new functionality.  Since `fitgalsim` requires GalSim, it cannot be run by travis, but we could test `specsim.fiberacceptance` using the `test.yaml` config with a small output from `fitgalsim` saved in `specsim/data/test/`.

**Comment by julienguy** [comment]
Results based on new method to get the galsim fiber acceptance as a function of sigma and offset.
I noted that adding a source axis ratio of 0.7 didn't change much the results.
For me, the PR is ready to merge.
fast-fiber-acceptance
fiber-acceptance-vs-sigma
fiber-acceptance-vs-offset

**Comment by moustakas** [comment]
This looks *awesome* but what about BGS targets, where the aperture effects are equally important?

**Comment by julienguy** [comment]
This discussion should go in the desisim PR :-)  https://github.com/desihub/desisim/pull/261
The BGS target profile properties (half light radius, fraction of disk and bulge) have to be defined in desisim/simexp.py in routine simulate_spectra which uses the fibermap info to decide on the source profile.
For the moment I used the same parameters as for LRGs, but you are welcome to tune this.

**Comment by dkirkby** [comment]
Everything looks good here, thanks!

Two questions:
 - Are we (@sbailey) comfortable changing the default behavior (in `desi.yaml`) to "fastsim", effectively deprecating the original `fiberloss-xxx.dat` tables in desimodel?
 - What is the minimum tag of desimodel required to use the "fastsim" mode? (i.e., containing `throughput/galsim-fiber-acceptance.fits`)

**Comment by sbailey** [comment]
> * Are we (@sbailey) comfortable changing the default behavior (in desi.yaml) to "fastsim", effectively deprecating the original fiberloss-xxx.dat tables in desimodel?

Yes.  This is more accurate than the previous tables without requiring heavyweight dependencies.

> * What is the minimum tag of desimodel required to use the "fastsim" mode? (i.e., containing throughput/galsim-fiber-acceptance.fits)

0.9.0

**Pull request merged**
