### PR TITLE
Calculate PSF truncation based on actual wavelength grid and PSF size

### LINKED ISSUE #12: Improve calculation of sparse resolution matrix
The following code from `quick.py` copies the logic of the [original IDL code](https://desi.lbl.gov/trac/browser/code/desimodel/trunk/pro/desi_quicksim.pro#L225), but needs several improvements to support arbitrary simulation grids:
```
        # Build a sparse matrix representation of the co-added resolution smoothing kernel.
        nhalf = 50
        nbins = wavelengthGrid.size
        sparseData = np.empty((2*nhalf*nbins,))
        sparseIndices = np.empty((2*nhalf*nbins,),dtype=np.int32)
        sparseIndPtr = np.empty((nbins+1,),dtype=np.int32)
        nextIndex = 0
        for bin in range(nbins):
            sparseIndPtr[bin] = nextIndex
            if bin >= nhalf and bin < nbins-nhalf and self.throughput[bin] > 0:
                lam = wavelengthGrid[bin]
                sigma = self.sigmaWavelength[bin]
                if sigma > 0:
                    psf = np.exp(-0.5*((wavelengthGrid[bin-nhalf:bin+nhalf]-lam)/sigma)**2)
                    psf /= np.sum(psf)
                    rng = slice(nextIndex,nextIndex+psf.size)
                    sparseIndices[rng] = range(bin-nhalf,bin+nhalf)
                    sparseData[rng] = psf
                    nextIndex += psf.size
        sparseIndPtr[-1] = nextIndex
        # The original IDL code uses the transpose of the correct smoothing kernel,
        # which corresponds to the second commented line below. We ultimately want the
        # kernel in CSR format since this is ~10% faster than CSC for the convolution.
        self.sparseKernel = sp.csc_matrix((sparseData,sparseIndices,sparseIndPtr),(nbins,nbins)).tocsr()
```
Issues to address here:
* The value of `nhalf` should be based on the wavelength grid and the typical PSF size.
* The first and last `nhalf` matrix columns should be filled with a truncated (un-normalized?) Gaussian psf instead of zeros.

### PR DESCRIPTION
**Pull request by dkirkby**
Fixes #12

Use the following regression test for changes:
```
specsim% quickspecsim --infile specsim/data/spectra/spec-ABmag22.0.dat --model qso --verbose
spec-ABmag22.0.dat g=22.00 r=22.00 i=22.00
Will simulate wavelengths 3500.300000 - 9999.700000 Ang with 0.100000 Ang spacing.
Running quick simulation.
Median S/N = 0.934, Total (S/N)^2 = 10441.6
```

### CODE REVIEW

**Comment by dkirkby** [comment]
@weaverba137 TravisCI [tests are failing](https://travis-ci.org/desihub/specsim/jobs/89983169) with an error I have not seen before, but which does not seem to be related to any changes I made:
```
...
$ conda update --yes conda
/home/travis/build.sh: line 41: conda: command not found
The command "conda update --yes conda" failed and exited with 127 during .
```
Have you seen this before, or any suggestions?

**Comment by dkirkby** [comment]
@sbailey The following test now gives more reasonable results:
```
import specsim
import astropy.units as u
import os

model = os.environ['SPECSIM_MODEL']
atmosphere = specsim.atmosphere.Atmosphere(skyConditions='dark', basePath=model)
qsim = specsim.quick.Quick(atmosphere=atmosphere, basePath=model)
qsim.setWavelengthGrid(5000.1, 5010-0.1, 0.1)

w = np.arange(5000, 5010, 0.1)
influx = np.ones(len(w)) * 1e-17
influx[50] = 10e-17
spectrum = specsim.spectrum.SpectralFluxDensity(
    w, influx, fluxUnits=u.erg/(u.s*u.cm**2*u.angstrom))

results = qsim.simulate('elg', spectrum, downsampling=1)
plt.plot(results.wave, results.srcflux / 10, label='Template / 10')
plt.plot(results.wave, results.obsflux, label='Observed')
plt.legend()
```
pr12

You should generally specify a simulation wavelength grid that extends ~5 sigma beyond the camera coverage, otherwise you get the unphysical edge effects seen here.

**Comment by weaverba137** [comment]
In the build script, where you have the line:
```
./miniconda.sh -b
```
Replace that with
```
./miniconda.sh -b -p $HOME/miniconda
```

**Comment by dkirkby** [comment]
@weaverba137 That works, thanks!

**Comment by dkirkby** [comment]
@sbailey I am ready to merge this, but let me know if you want to review the changes first.

**Comment by sbailey** [comment]
Whoops, sorry, I had missed that you had assigned it to me to review.  Go ahead and merge.  Thanks.

**Pull request merged**
